apiVersion: v1
kind: Namespace
metadata:
  name: microservices
  labels:
    name: microservices
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: microservices
data:
  NODE_ENV: "production"
  JWT_SECRET: "your-super-secret-jwt-key-here"
  API_KEY: "your-api-key-here"
  DATABASE_URL: "mongodb://admin:password123@mongodb:27017/microservices?authSource=admin"
  REDIS_URL: "redis://redis-service:6379"